package io.kaiteyo.kjd.export

import io.kaiteyo.kjd.source.AttributionManifest
import io.kaiteyo.kjd.source.BuiltinSources
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Verifies the third-party attribution generation: machine-readable JSON and
 * human-readable Markdown both derive from the same manifest and cover every
 * ingested source and license.
 */
class AttributionWriterTest {

    private fun tempDir(): File {
        val dir = File.createTempFile("kjd-attrib-", "")
        dir.delete()
        dir.mkdirs()
        dir.deleteOnExit()
        return dir
    }

    private fun manifest(): AttributionManifest = AttributionManifest(
        platform = "Test Platform",
        generatedBy = "test-1.0.0",
        generatedAt = "2026-01-01T00:00:00Z",
        schemaVersion = 2,
        sources = BuiltinSources.all
    )

    @Test
    fun writesJsonAndMarkdown() {
        val dir = tempDir()
        val (jsonFile, mdFile) = AttributionWriter().write(manifest(), dir)

        assertTrue(jsonFile.isFile)
        assertTrue(mdFile.isFile)
        assertEquals("THIRD_PARTY_DATA.json", jsonFile.name)
        assertEquals("THIRD_PARTY_DATA.md", mdFile.name)
        dir.deleteRecursively()
    }

    @Test
    fun markdownCoversEverySourceAndLicense() {
        val dir = tempDir()
        val (_, mdFile) = AttributionWriter().write(manifest(), dir)
        val md = mdFile.readText()

        BuiltinSources.all.forEach { source ->
            assertTrue(md.contains(source.name), "markdown must mention ${source.name}")
            assertTrue(md.contains(source.license.name), "markdown must mention ${source.license.name}")
            assertTrue(md.contains(source.attribution), "markdown must include attribution for ${source.name}")
        }
        assertTrue(md.contains("generated by test-1.0.0", ignoreCase = true))
        dir.deleteRecursively()
    }

    @Test
    fun jsonIsParsableAndComplete() {
        val dir = tempDir()
        val (jsonFile, _) = AttributionWriter().write(manifest(), dir)
        val parsed = kotlinx.serialization.json.Json { ignoreUnknownKeys = true }
            .decodeFromString(AttributionManifest.serializer(), jsonFile.readText())

        assertEquals(BuiltinSources.all.size, parsed.sources.size)
        assertEquals("test-1.0.0", parsed.generatedBy)
        assertEquals(2, parsed.schemaVersion)
        dir.deleteRecursively()
    }
}
