package ua.syt0r.kanji.presentation.common.resources.brand

import androidx.compose.foundation.Image
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.ContentScale
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.painterResource
import ua.syt0r.kanji.Res
import ua.syt0r.kanji.kaiteyo_mark
import ua.syt0r.kanji.presentation.common.theme.BaseMode
import ua.syt0r.kanji.presentation.common.theme.LocalBaseMode

// ============================================================
// KAITEYO BRAND ASSETS — ONE SOURCE, ONE API, MANY SURFACES
//
// Every UI surface (Home, About, onboarding, window chrome,
// installer, …) resolves Kaiteyo branding through this single
// object instead of scattering raw drawable names through the
// app. The drawables themselves are generated by the brand
// pipeline (`brand/scripts/sync-assets.sh`) from the source
// assets in `brand/source/`, so replacing a logo later is a
// drop-in file swap, not a code hunt.
//
//   brand/source/  →  validate  →  brand/processed/  →
//   core composeResources drawable  →  BrandAssets  →  UI
//
// Theme awareness: variants are selected by the active base
// mode (Light uses the light variant, everything else the
// dark one). Every role falls back to a deliberately neutral
// default when no dedicated variant has been supplied — the
// Kaiteyo mark is self-contained (brand tile + brush stroke),
// so it reads correctly on any surface.
// ============================================================

object BrandAssets {

    // --- Marks (compact symbol) -------------------------------------------
    // The Kaiteyo mark: brush-stroke + accent dot on the brand tile.
    // Theme-agnostic by design, so light/dark variants fall back to it.
    val AppMark: DrawableResource = Res.drawable.kaiteyo_mark
    val AppMarkLight: DrawableResource = Res.drawable.kaiteyo_mark
    val AppMarkDark: DrawableResource = Res.drawable.kaiteyo_mark

    // --- Logos (wide horizontal wordmark) ---------------------------------
    // Falls back to the mark until a wide logo is supplied to the brand
    // pipeline (brand/source/logos/app-logo.svg → kaiteyo_logo.xml).
    val AppLogo: DrawableResource = Res.drawable.kaiteyo_mark
    val AppLogoLight: DrawableResource = Res.drawable.kaiteyo_mark
    val AppLogoDark: DrawableResource = Res.drawable.kaiteyo_mark
}

/** How a brand asset picks its variant for the active theme. */
enum class BrandAssetVariant {
    /** Follow the active base mode (Light → light variant, else dark). */
    Auto,

    /** Force the light variant. */
    Light,

    /** Force the dark variant. */
    Dark
}

/** Resolves the theme-appropriate [DrawableResource] for a role's variants. */
@Composable
fun brandAsset(
    base: DrawableResource,
    light: DrawableResource = base,
    dark: DrawableResource = base,
    variant: BrandAssetVariant = BrandAssetVariant.Auto
): DrawableResource = when (variant) {
    BrandAssetVariant.Light -> light
    BrandAssetVariant.Dark -> dark
    BrandAssetVariant.Auto -> when (LocalBaseMode.current) {
        BaseMode.Light, BaseMode.Sepia, BaseMode.Cream, BaseMode.Paper -> light
        else -> dark
    }
}

/**
 * Renders a Kaiteyo brand asset (default: the app mark) with the theme-aware
 * variant already resolved. Decorative placements should pass `null` for
 * [contentDescription]; standalone identity placements (About, splash, …)
 * should describe the asset (e.g. "Kaiteyo").
 */
@Composable
fun BrandImage(
    modifier: Modifier = Modifier,
    role: DrawableResource = BrandAssets.AppMark,
    lightRole: DrawableResource = role,
    darkRole: DrawableResource = role,
    variant: BrandAssetVariant = BrandAssetVariant.Auto,
    contentDescription: String? = "Kaiteyo",
    contentScale: ContentScale = ContentScale.Fit
) {
    Image(
        painter = painterResource(brandAsset(role, lightRole, darkRole, variant)),
        contentDescription = contentDescription,
        modifier = modifier,
        contentScale = contentScale
    )
}

/** The compact Kaiteyo mark (brush-stroke tile), theme-aware. */
@Composable
fun BrandMark(
    modifier: Modifier = Modifier,
    variant: BrandAssetVariant = BrandAssetVariant.Auto,
    contentDescription: String? = "Kaiteyo"
) {
    BrandImage(
        modifier = modifier,
        role = BrandAssets.AppMark,
        lightRole = BrandAssets.AppMarkLight,
        darkRole = BrandAssets.AppMarkDark,
        variant = variant,
        contentDescription = contentDescription
    )
}

/** The wide Kaiteyo logo (falls back to the mark until a logo is supplied). */
@Composable
fun BrandLogo(
    modifier: Modifier = Modifier,
    variant: BrandAssetVariant = BrandAssetVariant.Auto,
    contentDescription: String? = "Kaiteyo"
) {
    BrandImage(
        modifier = modifier,
        role = BrandAssets.AppLogo,
        lightRole = BrandAssets.AppLogoLight,
        darkRole = BrandAssets.AppLogoDark,
        variant = variant,
        contentDescription = contentDescription
    )
}
