package io.kaiteyo.kjd.export

import io.kaiteyo.kjd.source.AttributionManifest
import io.kaiteyo.kjd.source.SourceMetadata
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File

/**
 * Generates the third-party data attribution files shipped with every KJD
 * release:
 *
 *   - `THIRD_PARTY_DATA.json` — machine-readable license manifest
 *   - `THIRD_PARTY_DATA.md`   — human-readable attribution summary
 *
 * Both are derived solely from the [AttributionManifest] embedded in the
 * generated database, so the shipped files and the database provenance can
 * never drift apart. The KJD code license (see the repository LICENSE) and
 * the data licenses remain explicitly distinct.
 */
class AttributionWriter(
    private val json: Json = Json { prettyPrint = true; encodeDefaults = true }
) {

    fun write(manifest: AttributionManifest, targetDirectory: File): Pair<File, File> {
        targetDirectory.mkdirs()
        val jsonFile = File(targetDirectory, "THIRD_PARTY_DATA.json")
        val mdFile = File(targetDirectory, "THIRD_PARTY_DATA.md")
        jsonFile.writeText(json.encodeToString(AttributionManifest.serializer(), manifest))
        mdFile.writeText(toMarkdown(manifest))
        return jsonFile to mdFile
    }

    fun toMarkdown(manifest: AttributionManifest): String = buildString {
        appendLine("# Third-party data attribution")
        appendLine()
        appendLine("This database was generated by ${manifest.platform} (generator ${manifest.generatedBy}, " +
            "schema v${manifest.schemaVersion}, generated ${manifest.generatedAt}).")
        appendLine()
        appendLine("The language data included in this database is the work of the following projects. " +
            "KJD does not claim ownership of any third-party content. Code and data licenses are distinct.")
        appendLine()
        appendLine("| Source | Version | License | Attribution |")
        appendLine("|---|---|---|---|")
        manifest.sources.forEach { source ->
            appendLine("| [${source.name}](${source.homepage}) | ${source.version} | " +
                "[${source.license.name}](${source.license.url}) | ${source.attribution} |")
        }
        appendLine()
        appendLine("## Licenses in detail")
        appendLine()
        manifest.sources.forEach { source ->
            appendLine("### ${source.name} — v${source.version}")
            appendLine()
            appendLine("- License: **${source.license.name}** (${source.license.url})")
            appendLine("- Redistribution permitted: ${if (source.license.allowsRedistribution) "yes" else "no"}")
            appendLine("- Attribution required: ${if (source.license.attributionRequired) "yes" else "no"}")
            appendLine("- Share-alike: ${if (source.license.shareAlike) "yes" else "no"}")
            appendLine("- Retrieved: ${source.retrievedAt.ifBlank { "not recorded" }}")
            appendLine("- Source URL: ${source.sourceUrl.ifBlank { source.homepage }}")
            if (source.redistributionNotes.isNotBlank()) {
                appendLine("- Redistribution notes: ${source.redistributionNotes}")
            }
            if (source.modificationNotes.isNotBlank()) {
                appendLine("- Transformation: ${source.modificationNotes}")
            }
            appendLine("- Attribution: ${source.attribution}")
            appendLine()
        }
        appendLine("---")
        appendLine("Generated by ${manifest.generatedBy} at ${manifest.generatedAt}.")
    }

    /** Convenience: build a manifest from source metadata directly. */
    fun write(sources: List<SourceMetadata>, generatedBy: String, schemaVersion: Int, targetDirectory: File): Pair<File, File> =
        write(
            AttributionManifest(
                platform = io.kaiteyo.kjd.KjdVersion.PLATFORM_NAME,
                generatedBy = generatedBy,
                generatedAt = java.time.Instant.now().toString(),
                schemaVersion = schemaVersion,
                sources = sources
            ),
            targetDirectory
        )
}
