package ua.syt0r.kanji.core.knowledge

import kotlinx.serialization.Serializable

// ============================================================
// MNEMONIC SYSTEM
// ------------------------------------------------------------
// Mnemonics are memory aids for learning kanji. Each kanji can
// have multiple mnemonics from different sources:
//
//   AUTHORITATIVE — human-authored, curated
//   AI — generated by AI, clearly labeled
//   USER — created by the user
//   COMMUNITY — shared by the community
//
// Every mnemonic carries metadata: source, confidence, rating.
// AI-generated content is NEVER silently presented as authoritative.
//
// NOTE: ContentSourceType / ContentConfidence are declared once, in
// LearningContent.kt (shared provenance vocabulary for all content).
// Mnemonics use those same enums — Ai = AiGenerated, User =
// UserGenerated. Do not redeclare them here.
// ============================================================

/**
 * A mnemonic for a kanji.
 */
@Serializable
data class KanjiMnemonic(
    /** The mnemonic text. */
    val text: String,
    /** Who created this mnemonic. */
    val source: ContentSourceType,
    /** Confidence in accuracy/usefulness. */
    val confidence: ContentConfidence = ContentConfidence.Medium,
    /** User rating (1-5, null = unrated). */
    val rating: Int? = null,
    /** Number of upvotes from community. */
    val upvotes: Int = 0,
    /** Language of the mnemonic text. */
    val language: String = "en",
    /** Optional: the keyword this mnemonic relates to. */
    val keyword: String? = null,
    /** Optional: which components this mnemonic uses. */
    val components: List<String> = emptyList(),
    /** Timestamp when created. */
    val createdAt: Long = 0L,
    /** Timestamp when last used. */
    val lastUsedAt: Long = 0L,
    /** How many times this mnemonic has been reviewed. */
    val useCount: Int = 0,
    /** Whether this mnemonic is currently active/selected. */
    val isActive: Boolean = true
)

/**
 * A formula represents the structural decomposition of a kanji
 * as a memory aid — e.g., "water (氵) + hand (又) = 取 (to take)".
 */
@Serializable
data class KanjiFormula(
    /** The formula text. */
    val text: String,
    /** Components involved. */
    val components: List<FormulaComponent>,
    /** Source type. */
    val source: ContentSourceType,
    /** Whether this is a structural or semantic formula. */
    val type: FormulaType,
    /** Confidence. */
    val confidence: ContentConfidence = ContentConfidence.Medium
)

/**
 * A component in a formula.
 */
@Serializable
data class FormulaComponent(
    /** The component character. */
    val character: String,
    /** The component's meaning. */
    val meaning: String,
    /** Role in the formula (semantic, phonetic, structural). */
    val role: FormulaRole,
    /** Stroke count of this component. */
    val strokeCount: Int? = null
)

/**
 * Formula types.
 */
enum class FormulaType(val label: String) {
    Structural("Structural — how the kanji is built"),
    Semantic("Semantic — meaning-based composition"),
    Phonetic("Phonetic — sound-based hints"),
    Story("Story — narrative memory aid"),
    Visual("Visual — shape-based memory aid")
}

/**
 * Roles a component can play in a formula.
 */
enum class FormulaRole(val label: String) {
    Semantic("Semantic — provides meaning"),
    Phonetic("Phonetic — provides sound hint"),
    Structural("Structural — provides shape"),
    Radial("Radical — Kangxi radical"),
    Variant("Variant — alternate form")
}

/**
 * A graph relationship between two knowledge entities.
 */
@Serializable
data class GraphRelationship(
    /** Source entity. */
    val sourceId: String,
    /** Source entity type. */
    val sourceType: GraphNodeType,
    /** Target entity. */
    val targetId: String,
    /** Target entity type. */
    val targetType: GraphNodeType,
    /** Relationship type. */
    val relationshipType: GraphEdgeType,
    /** Weight/strength of this relationship (0.0–1.0). */
    val weight: Float = 1.0f,
    /** Label for the edge. */
    val label: String? = null
)

/**
 * Node types in the knowledge graph.
 */
enum class GraphNodeType(val label: String) {
    Kanji("Kanji"),
    Radical("Radical"),
    Component("Component"),
    Word("Word"),
    Sentence("Sentence"),
    Grammar("Grammar"),
    Lesson("Lesson"),
    Course("Course")
}

/**
 * Edge types in the knowledge graph.
 */
enum class GraphEdgeType(val label: String) {
    Contains("contains"),
    ComponentOf("component of"),
    RadicalOf("radical of"),
    PhoneticRelation("phonetic relation"),
    SemanticRelation("semantic relation"),
    VariantOf("variant of"),
    AppearsIn("appears in"),
    CompoundOf("compound of"),
    ExampleOf("example of"),
    PrerequisiteOf("prerequisite of"),
    RelatedTo("related to"),
    UsesKanji("uses kanji"),
    HasReading("has reading"),
    HasMeaning("has meaning"),
    UsedInWord("used in word"),
    UsedInSentence("used in sentence")
}

/**
 * Mnemonic store — manages mnemonics for kanji.
 * Supports loading, saving, rating, and AI generation.
 */
class MnemonicStore {

    private val mnemonics = mutableMapOf<String, MutableList<KanjiMnemonic>>()
    private val formulas = mutableMapOf<String, MutableList<KanjiFormula>>()

    /**
     * Get all mnemonics for a kanji, sorted by priority:
     * active first, then by source (authoritative > user > community > AI),
     * then by rating.
     */
    fun getMnemonics(kanji: String): List<KanjiMnemonic> {
        return (mnemonics[kanji] ?: emptyList())
            .filter { it.isActive }
            .sortedWith(compareBy<KanjiMnemonic> {
                when (it.source) {
                    ContentSourceType.Authoritative -> 0
                    ContentSourceType.UserGenerated -> 1
                    ContentSourceType.Community -> 2
                    ContentSourceType.AiGenerated -> 3
                    ContentSourceType.Derived -> 4
                }
            }.thenByDescending { it.rating ?: 0 }
                .thenByDescending { it.upvotes })
    }

    /**
     * Get the best mnemonic for a kanji.
     */
    fun getBestMnemonic(kanji: String): KanjiMnemonic? {
        return getMnemonics(kanji).firstOrNull()
    }

    /**
     * Add a mnemonic for a kanji.
     */
    fun addMnemonic(kanji: String, mnemonic: KanjiMnemonic) {
        mnemonics.getOrPut(kanji) { mutableListOf() }.add(mnemonic)
    }

    /**
     * Rate a mnemonic (1-5).
     */
    fun rateMnemonic(kanji: String, index: Int, rating: Int) {
        mnemonics[kanji]?.getOrNull(index)?.let { existing ->
            val updated = existing.copy(
                rating = rating.coerceIn(1, 5),
                lastUsedAt = System.currentTimeMillis(),
                useCount = existing.useCount + 1
            )
            mnemonics[kanji]?.set(index, updated)
        }
    }

    /**
     * Add a formula for a kanji.
     */
    fun addFormula(kanji: String, formula: KanjiFormula) {
        formulas.getOrPut(kanji) { mutableListOf() }.add(formula)
    }

    /**
     * Get all formulas for a kanji.
     */
    fun getFormulas(kanji: String): List<KanjiFormula> {
        return formulas[kanji] ?: emptyList()
    }

    /**
     * Get the best formula for a kanji.
     */
    fun getBestFormula(kanji: String): KanjiFormula? {
        return getFormulas(kanji).firstOrNull()
    }

    /**
     * Mark a mnemonic as inactive (user chose a different one).
     */
    fun deactivateMnemonic(kanji: String, index: Int) {
        mnemonics[kanji]?.getOrNull(index)?.let { existing ->
            mnemonics[kanji]?.set(index, existing.copy(isActive = false))
        }
    }

    /**
     * Clear all mnemonics for a kanji.
     */
    fun clearMnemonics(kanji: String) {
        mnemonics.remove(kanji)
    }

    /**
     * Clear all formulas for a kanji.
     */
    fun clearFormulas(kanji: String) {
        formulas.remove(kanji)
    }

    /**
     * Get statistics for a kanji's mnemonics.
     */
    fun getStats(kanji: String): MnemonicStats {
        val all = mnemonics[kanji] ?: emptyList()
        val bySource = all.groupBy { it.source }
        return MnemonicStats(
            total = all.size,
            bySource = bySource.mapValues { it.value.size },
            averageRating = all.mapNotNull { it.rating }.average().let {
                if (it.isNaN()) null else it
            },
            hasAuthoritative = bySource.containsKey(ContentSourceType.Authoritative),
            hasUser = bySource.containsKey(ContentSourceType.UserGenerated),
            hasAi = bySource.containsKey(ContentSourceType.AiGenerated)
        )
    }
}

/**
 * Statistics for a kanji's mnemonics.
 */
data class MnemonicStats(
    val total: Int,
    val bySource: Map<ContentSourceType, Int>,
    val averageRating: Double?,
    val hasAuthoritative: Boolean,
    val hasUser: Boolean,
    val hasAi: Boolean
)
