"""kaiteyo clean — safe cleanup utilities.

Two tiers, never mixed silently:

  SAFE        CLI caches and tool artifacts (our own .kaiteyo cache files,
              __pycache__ under tools/cli). Removed with confirmation.
  DESTRUCTIVE Gradle outputs (build/, .gradle/, .kotlin/) — regenerated by
              the build, but listed and confirmed loudly.

Source code is never deleted by this command.
"""

from __future__ import annotations

import argparse
import pathlib

from ..config import PROJECT_CACHE_DIR, USER_CONFIG_DIR
from ..context import Context
from ..errors import CliError, ABORT, OK
from ..registry import Command


def _project_cache(ctx: Context) -> pathlib.Path:
    root = ctx.require_root("The clean command")
    return root / PROJECT_CACHE_DIR


def _pycache_dirs(root: pathlib.Path) -> list[pathlib.Path]:
    cli_dir = root / "tools" / "cli"
    return list(cli_dir.rglob("__pycache__")) if cli_dir.is_dir() else []


def _safe_targets(ctx: Context) -> list[pathlib.Path]:
    targets: list[pathlib.Path] = []
    root = ctx.require_root("The clean command")
    cache = _project_cache(ctx)
    for name in ("gradle-tasks.json", "config.json"):
        path = cache / name
        if path.is_file():
            targets.append(path)
    targets.extend(_pycache_dirs(root))
    return targets


def _cmd_clean(args: argparse.Namespace, ctx: Context) -> int:
    out = ctx.out
    if args.build:
        root = ctx.require_root("The clean command")
        out.warn("This removes Gradle build outputs: build/, .gradle/, .kotlin/.")
        out.warn("They are regenerated on the next build. Source code is untouched.")
        if args.dry_run:
            for name in ("build", ".gradle", ".kotlin"):
                path = root / name
                if path.exists():
                    out.line(f"  would remove {path}")
            return OK
        if not ctx.confirm("Remove build outputs?", default=False):
            raise CliError("Clean cancelled.", code=ABORT)
        removed = 0
        for name in ("build", ".gradle", ".kotlin"):
            path = root / name
            if path.exists():
                _rmtree(path)
                out.ok(f"Removed {path}")
                removed += 1
        if removed == 0:
            out.info("Nothing to remove.")
        return OK

    targets = _safe_targets(ctx)
    if args.dry_run:
        for target in targets:
            out.line(f"  would remove {target}")
        if not targets:
            out.info("No safe-cleanup targets found.")
        return OK
    if not targets:
        out.info("No safe-cleanup targets found (CLI caches / __pycache__).")
        return OK
    out.info("Safe cleanup targets (CLI caches and tool artifacts only):")
    for target in targets:
        out.line(f"  {target}")
    if not ctx.confirm("Remove these?", default=False):
        raise CliError("Clean cancelled.", code=ABORT)
    for target in targets:
        _rmtree(target)
        out.ok(f"Removed {target}")
    return OK


def _rmtree(path: pathlib.Path) -> None:
    import shutil

    if path.is_dir():
        shutil.rmtree(path, ignore_errors=True)
    else:
        path.unlink(missing_ok=True)


def build(sub: argparse.ArgumentParser, common: argparse.ArgumentParser | None = None) -> None:
    sub.add_argument("--build", action="store_true",
                     help="destructive: remove Gradle build outputs (confirmed)")
    sub.add_argument("--dry-run", action="store_true",
                     help="list what would be removed, change nothing")


command = Command(
    name="clean",
    help="Remove CLI caches / tool artifacts (safe) or Gradle build outputs (confirmed)",
    description=(
        "Safe cleanup removes CLI caches and __pycache__ under tools/cli.\n"
        "Destructive cleanup (--build) removes Gradle build outputs and is\n"
        "always confirmed. Source code is never deleted.\n\n"
        "Examples:\n"
        "  kaiteyo clean --dry-run\n"
        "  kaiteyo clean\n"
        "  kaiteyo clean --build --dry-run\n"
        "  kaiteyo clean --build\n"
    ),
    build=build,
    run=lambda args, ctx: _cmd_clean(args, ctx),
)
