; ============================================================================
; Kaiteyo — Premium Windows Installer (Inno Setup 6.4+)
;
; A branded, dark-mode-aware installer for the Kaiteyo desktop app.
; - Modern wizard (WizardStyle=modern dynamic) — light/dark follows Windows
; - Install / Upgrade / Repair / Modify / Uninstall with data preservation
; - Silent install: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
; - Component tasks, install-location memory, launch-after-install
;
; Build:  powershell -File installer/windows/build.ps1 -Version 2.2.1
; ============================================================================

#ifndef MyAppVersion
  #define MyAppVersion "2.2.1"
#endif
#ifndef MyAppPublisher
  #define MyAppPublisher "syt0r"
#endif
#ifndef MyAppName
  #define MyAppName "Kaiteyo"
#endif
#ifndef MyAppId
  #define MyAppId "12c852a8-6e21-41a7-bd47-3bec9ff5c5df"
#endif

#define MyAppExeName "Kaiteyo.exe"
#define MyAppAssocExt "kaiteyo"
#define MyAppAssocKey "Kaiteyo.Backup"

[Setup]
AppId={{#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL=https://github.com/ValiantZippu/Kaiteyo
AppSupportURL=https://github.com/ValiantZippu/Kaiteyo/issues
AppUpdatesURL=https://github.com/ValiantZippu/Kaiteyo/releases
AppComments=Premium Japanese language learning app

; ---- Branding (generated by installer/scripts/generate-assets.sh) ----
; Paths are relative to THIS script's directory (installer/windows/), so the
; shared assets live one level up.
SetupIconFile=..\assets\generated\windows\kaiteyo.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
WizardStyle=modern dynamic includetitlebar
WizardImageFile=..\assets\generated\windows\banner.bmp
WizardImageFileDynamicDark=..\assets\generated\windows\banner-dark.bmp
WizardSmallImageFile=..\assets\generated\windows\welcome.bmp

; ---- Layout & privileges ----
DefaultDirName={autopf}\Kaiteyo
DefaultGroupName=Kaiteyo
DisableProgramGroupPage=yes
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=build\kaiteyo-{#MyAppVersion}
OutputBaseFilename=Kaiteyo-Setup-{#MyAppVersion}
Compression=lzma2/ultra64
SolidCompression=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0.19044
CloseApplications=yes
RestartApplications=no
UsePreviousAppDir=yes
UsePreviousTasks=yes
AllowNoIcons=yes
; Data lives in %LOCALAPPDATA%\Kaiteyo (never under {app}) so upgrades,
; repairs and uninstalls can never touch study data.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "Includes\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:TaskDesktopIcon}"; GroupDescription: "{cm:TaskGroupShortcuts}"; Flags: unchecked
Name: "startmenu"; Description: "{cm:TaskStartMenu}"; GroupDescription: "{cm:TaskGroupShortcuts}"; Flags: checkedonce
Name: "fileassoc"; Description: "{cm:TaskFileAssoc}"; GroupDescription: "{cm:TaskGroupIntegration}"; Flags: unchecked
Name: "autoupdate"; Description: "{cm:TaskAutoUpdate}"; GroupDescription: "{cm:TaskGroupIntegration}"; Flags: checkedonce
Name: "dictionary"; Description: "{cm:TaskDictionary}"; GroupDescription: "{cm:TaskGroupContent}"; Flags: unchecked

[Files]
; Application payload — produced by :desktopApp:createDistributable (jpackage image).
Source: "..\..\desktopApp\build\compose\binaries\main\app\Kaiteyo\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Optional dictionary starter pack — CI stages this folder before building.
; The starter pack is staged by build.ps1 / CI (mkdir desktopApp/build/dictionary-starter-pack)
; before ISCC runs, so this source always exists at compile time.
Source: "..\..\desktopApp\build\dictionary-starter-pack\*"; DestDir: "{localappdata}\Kaiteyo\dictionaries"; Flags: ignoreversion recursesubdirs createallsubdirs onlyifdoesntexist; Tasks: dictionary

[Icons]
Name: "{group}\Kaiteyo"; Filename: "{app}\{#MyAppExeName}"; Tasks: startmenu
Name: "{group}\{cm:UninstallProgram,Kaiteyo}"; Filename: "{uninstallexe}"; Tasks: startmenu
Name: "{autodesktop}\Kaiteyo"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
; Future-ready file association (registered only when the task is selected).
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "Kaiteyo Backup Archive"; Flags: uninsdeletekey; Tasks: fileassoc
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"; Tasks: fileassoc
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Tasks: fileassoc
Root: HKA; Subkey: "Software\Classes\.{#MyAppAssocExt}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocKey}"; Flags: uninsdeletevalue; Tasks: fileassoc

; Version marker — lets scripts and the app detect the installed version.
Root: HKCU; Subkey: "Software\Kaiteyo"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Kaiteyo"; ValueType: string; ValueName: "Version"; ValueData: "{#MyAppVersion}"; Flags: uninsdeletekey

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchApp,Kaiteyo}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Only temp artifacts of the app itself; study data & settings live in
; %LOCALAPPDATA%\Kaiteyo and are handled by the uninstaller's keep/remove
; page (see Includes\Uninstall.iss).
Type: filesandordirs; Name: "{app}\logs"

[CustomMessages]
english.LaunchApp=Launch %1 now
english.TaskGroupShortcuts=Shortcuts
english.TaskDesktopIcon=Create a &desktop shortcut
english.TaskStartMenu=Add a &Start Menu folder
english.TaskGroupIntegration=Integration
english.TaskFileAssoc=Associate .kaiteyo backup &files with Kaiteyo
english.TaskAutoUpdate=Enable &automatic update checks
english.TaskGroupContent=Content
english.TaskDictionary=Install the free dictionary &starter pack
english.UninstallProgram=Uninstall %1

japanese.LaunchApp=%1 を今すぐ起動
japanese.TaskGroupShortcuts=ショートカット
japanese.TaskDesktopIcon=デスクトップにショートカットを作成(&D)
japanese.TaskStartMenu=スタートメニューにフォルダを追加(&S)
japanese.TaskGroupIntegration=統合
japanese.TaskFileAssoc=.kaiteyo バックアップファイルを関連付け(&F)
japanese.TaskAutoUpdate=自動更新チェックを有効化(&A)
japanese.TaskGroupContent=コンテンツ
japanese.TaskDictionary=無料辞書スターターパックをインストール(&I)
japanese.UninstallProgram=%1 をアンインストール

#include "Includes\Branding.iss"
#include "Includes\Code.iss"
#include "Includes\Uninstall.iss"
