#!/usr/bin/env bash
# ============================================================================
# Kaiteyo — Arch Linux package builder
#
# Generates installer/linux/arch/PKGBUILD from the single source of truth
# (installer/common/version.json) + the actual release AppImage (whose sha256
# is computed here, never guessed), then builds the .pkg.tar.zst with makepkg.
#
# Usage: bash installer/linux/arch/build.sh [version]
#   Requires: the AppImage built first — bash installer/linux/appimage/build.sh
#   Requires: makepkg (base-devel) on the build host.
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
HERE="$ROOT/installer/linux/arch"
VERSION="${1:-$(jq -r '.version' "$ROOT/installer/common/version.json")}"

# The AppImage is the source artifact (same one the docs point users at).
APPIMAGE="$ROOT/installer/linux/appimage/out/Kaiteyo-$VERSION-x86_64.AppImage"
[[ -f "$APPIMAGE" ]] || {
    echo "error: $APPIMAGE missing — run bash installer/linux/appimage/build.sh $VERSION first" >&2
    exit 1
}

SHA256="$(sha256sum "$APPIMAGE" | cut -d' ' -f1)"
PKGREL="1"

echo "== Generating PKGBUILD (kaiteyo-$VERSION-$PKGREL) =="

# ---------------------------------------------------------------------------
# PKGBUILD template — ${VAR} placeholders are filled by this script only.
# Never commit a PKGBUILD with a stale version or guessed checksum.
# ---------------------------------------------------------------------------
cat > "$HERE/PKGBUILD" <<EOF
# Maintainer: Kaiteyo maintainers <syt0r@users.noreply.github.com>
# Contributor: Kaiteyo contributors — see CONTRIBUTING.md
#
# Binary package: repackages the official Kaiteyo AppImage with full desktop
# integration (.desktop, hicolor icons, AppStream metainfo). Generated by
# installer/linux/arch/build.sh from installer/common/version.json — do not
# edit by hand; version and checksums are filled in at build time.

pkgname=kaiteyo
pkgver=${VERSION}
pkgrel=${PKGREL}
pkgdesc="Japanese language learning app with writing exercises, flashcards and a built-in dictionary"
arch=('x86_64')
url="https://github.com/ValiantZippu/Kaiteyo"
license=('GPL3')
depends=('libx11' 'libxext' 'libxi' 'libxrender' 'libxtst' 'libgl' 'fontconfig')
optdepends=('vlc: VLC media backend' 'mpv: mpv media backend')
source=("Kaiteyo-${VERSION}-x86_64.AppImage::file://${APPIMAGE}")
sha256sums=('${SHA256}')

package() {
    # Payload — the AppImage is self-contained (bundled JRE), placed under /opt.
    install -Dm755 "\${srcdir}/Kaiteyo-${VERSION}-x86_64.AppImage" \
        "\${pkgdir}/opt/kaiteyo/Kaiteyo.AppImage"

    # Launcher wrapper — the AppImage is a single file; exec it directly.
    cat > "\${pkgdir}/usr/bin/kaiteyo" <<'WRAPPER'
#!/bin/sh
exec /opt/kaiteyo/Kaiteyo.AppImage "\$@"
WRAPPER
    chmod +x "\${pkgdir}/usr/bin/kaiteyo"

    # Desktop entry + AppStream metainfo (shared metadata, not duplicates).
    install -Dm644 "${ROOT}/installer/linux/appimage/io.github.syt0r.kaiteyo.desktop" \
        "\${pkgdir}/usr/share/applications/io.github.syt0r.kaiteyo.desktop"
    install -Dm644 "${ROOT}/installer/linux/appimage/io.github.syt0r.kaiteyo.metainfo.xml" \
        "\${pkgdir}/usr/share/metainfo/io.github.syt0r.kaiteyo.metainfo.xml"

    # Hicolor icon theme.
    ICONS="${ROOT}/installer/assets/generated/linux"
    for size in 16 32 48 64 128 256 512; do
        install -Dm644 "\$ICONS/kaiteyo-\$size.png" \
            "\${pkgdir}/usr/share/icons/hicolor/\${size}x\${size}/apps/io.github.syt0r.kaiteyo.png"
    done
    install -Dm644 "\$ICONS/kaiteyo.svg" \
        "\${pkgdir}/usr/share/icons/hicolor/scalable/apps/io.github.syt0r.kaiteyo.svg"
}
EOF

echo "== PKGBUILD written: $HERE/PKGBUILD =="

WORK="$HERE/work"
rm -rf "$WORK"
mkdir -p "$WORK"
cp "$HERE/PKGBUILD" "$WORK/PKGBUILD"

echo "== Building (makepkg) =="
cd "$WORK"
makepkg -f --noconfirm

OUT="$HERE/out"
mkdir -p "$OUT"
mv "$WORK"/kaiteyo-*.pkg.tar.* "$OUT/"
echo "== Done: $(ls -1 "$OUT") =="
